image: maven:latest

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-process
    -DinstallAtEnd=true
    -DdeployAtEnd=true
    
build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

test-job:
  stage: test
  parallel:
    matrix:
      - BROWSER: ["chrome", "edge", "firefox"]
  services:
    - name: selenium/standalone-$BROWSER
      alias: $BROWSER
  script:
    - apt update -y && apt upgrade -y
    - apt install openjdk-25-jdk -y
    - apt install maven -y
    - export TEST_BROWSER=$BROWSER
    - mvn $MVN_CLI_OPTS clean verify
  artifacts:
    paths:
      - target/surefire-reports/**
    when: always
    expire_in: 30 days
