AUTConnectionString=jdbc:sqlserver://localhost:1433;databaseName=EmployeeDB;user=sa;password=abc123
ReportingConnectionString=jdbc:sqlserver://localhost:1433;databaseName=EARS_DB;user=sa;password=abc123
LogPath=/home/mel/IdeaProjects/selenium_framework_java/SeleniumTestResults
ExcelSheetPath=/media/mel/Mel SSD/python_workspace
DriverType=com.microsoft.sqlserver.jdbc.SQLServerDriver
BrowserType=Chrome
AUT=http://localhost:64429/
WebDriverWait=30
HighlightElement=true
WebDriverManagerEnabled=false
Headless=true